[project]
name = "panza"
version = "0.1.0"
description = "Experimental sqlite caching and concurrency limiting"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv]
dev-dependencies = [
    "pytest-asyncio>=0.24.0",
    "pytest>=8.3.3",
]
